import { Dynamic } from 'solid-js/web';
import {
  Zap, PlusCircle, Layers, Sliders, SlidersVertical, Puzzle, ChevronDown, ChevronRight,
  Trash2, DownloadCloud, Music, ShieldCheck, Database,
  AlertCircle, AlertTriangle, CheckCircle2, Loader, Terminal,
  Search, Filter, Funnel, Film, Play, ExternalLink,
  X, PlayCircle, SkipBack, Pause, SkipForward,
  LayoutDashboard, LayoutGrid, Move, GripVertical, Grid3x3, Plus, Minus, Settings, Settings2, BarChart2, ChartNoAxesColumn, HardDrive, Clock, Download, Edit2, Pen, Check, CornerRightDown,
  RefreshCw, RotateCcw, RotateCw, History, Info, Key, Star, User,
  Image, Video, FileAudio, WifiOff, Maximize2, Pencil,
  PanelLeftOpen, PanelLeftClose, Wifi, ChevronsUpDown, ArrowLeft,
  ListPlus, ListMusic, CirclePlus,
} from 'lucide-solid';

const iconMap = {
  'zap': Zap,
  'plus-circle': PlusCircle,
  'circle-plus': CirclePlus,
  'layers': Layers,
  'sliders': Sliders,
  'sliders-vertical': SlidersVertical,
  'puzzle': Puzzle,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'trash-2': Trash2,
  'download-cloud': DownloadCloud,
  'cloud-download': DownloadCloud,
  'music': Music,
  'shield-check': ShieldCheck,
  'database': Database,
  'alert-circle': AlertCircle,
  'circle-alert': AlertCircle,
  'alert-triangle': AlertTriangle,
  'check-circle-2': CheckCircle2,
  'circle-check': CheckCircle2,
  'loader': Loader,
  'terminal': Terminal,
  'search': Search,
  'filter': Filter,
  'funnel': Funnel,
  'film': Film,
  'play': Play,
  'external-link': ExternalLink,
  'x': X,
  'play-circle': PlayCircle,
  'circle-play': PlayCircle,
  'skip-back': SkipBack,
  'pause': Pause,
  'skip-forward': SkipForward,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'move': Move,
  'grip': GripVertical,
  'grip-vertical': GripVertical,
  'grid': Grid3x3,
  'grid-3x3': Grid3x3,
  'plus': Plus,
  'minus': Minus,
  'settings': Settings,
  'settings-2': Settings2,
  'bar-chart': BarChart2,
  'chart-no-axes-column': ChartNoAxesColumn,
  'hard-drive': HardDrive,
  'clock': Clock,
  'download': Download,
  'edit-2': Edit2,
  'pen': Pen,
  'check': Check,
  'corner-right-down': CornerRightDown,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'history': History,
  'info': Info,
  'key': Key,
  'star': Star,
  'user': User,
  'image': Image,
  'video': Video,
  'file-audio': FileAudio,
  'wifi-off': WifiOff,
  'maximize-2': Maximize2,
  'pencil': Pencil,
  'panel-left-open': PanelLeftOpen,
  'panel-left-close': PanelLeftClose,
  'wifi': Wifi,
  'chevrons-up-down': ChevronsUpDown,
  'arrow-left': ArrowLeft,
  'list-plus': ListPlus,
  'list-music': ListMusic,
};

export default function Icon(props) {
  const component = iconMap[props.name];
  if (!component) {
    return <svg class={props.class} viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/></svg>;
  }
  return <Dynamic component={component} class={props.class} />;
}
